version: "3"
services:
  awspython:
    build: .
    container_name: awspython
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      # - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      # - AWS_CONFIG_FILE=/root/.aws/config
      # - AWS_ACCESS_KEY_ID=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      # - AWS_SECRET_ACCESS_KEY=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
      # - AWS_PROFILE=default
    networks:
      - default
    stdin_open: true
    tty: true
    volumes:
      - ./:/mounted-files
      - ${HOME}/.aws:/root/.aws
      - ${HOME}/.aws-login:/root/.aws-login
    working_dir: "/mounted-files"
networks:
  default:
    driver: "bridge"
