AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Create custom patch baselines so that Inspector CVE scans will be happy

Parameters:

  PatchApprovalDelayParam:
    Default: 0
    Description: How many days to delay before approving patches?
    Type: Number

Resources:

  AmazonLinuxPatchBaseline:
    Type: "AWS::SSM::PatchBaseline"
    Properties:
      Name: cu-cit-cloud-team-patching-AmazonLinux
      # Options: WINDOWS, AMAZON_LINUX, AMAZON_LINUX_2, UBUNTU, REDHAT_ENTERPRISE_LINUX, SUSE, and CENTOS
      OperatingSystem: AMAZON_LINUX
      Description: "Patch baseline for use with https://github.com/CU-CommunityApps/ct-patching-scanning"
      PatchGroups:
        - cu-cit-cloud-team-patching
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
              # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
              PatchFilters:
                # - Key: PRODUCT
                #   Values:
                #     - "*"
                - Key: CLASSIFICATION
                  Values:
                    - Security
                    - Bugfix
            ApproveAfterDays: !Ref PatchApprovalDelayParam
            # ComplianceLevel: String
            # EnableNonSecurity: Boolean
      # ApprovedPatches:
      #   - String
      # ApprovedPatchesComplianceLevel: CRITICAL
      # ApprovedPatchesEnableNonSecurity: false
      # RejectedPatches:
      #   - String
      # RejectedPatchesAction:
      #   - String
      # GlobalFilters:
      #   PatchFilterGroup
      # Sources : PatchSource

  AmazonLinux2PatchBaseline:
    Type: "AWS::SSM::PatchBaseline"
    Properties:
      Name: cu-cit-cloud-team-patching-AmazonLinux2
      # Options: WINDOWS, AMAZON_LINUX, AMAZON_LINUX_2, UBUNTU, REDHAT_ENTERPRISE_LINUX, SUSE, and CENTOS
      OperatingSystem: AMAZON_LINUX_2
      Description: "Patch baseline for use with https://github.com/CU-CommunityApps/ct-patching-scanning"
      PatchGroups:
        - cu-cit-cloud-team-patching
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
              # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
              PatchFilters:
                # - Key: PRODUCT
                #   Values:
                #     - "*"
                - Key: CLASSIFICATION
                  Values:
                    - Security
                    - Bugfix
            ApproveAfterDays: !Ref PatchApprovalDelayParam
            # ComplianceLevel: String
            # EnableNonSecurity: Boolean
      # ApprovedPatches:
      #   - String
      # ApprovedPatchesComplianceLevel: CRITICAL
      # ApprovedPatchesEnableNonSecurity: false
      # RejectedPatches:
      #   - String
      # RejectedPatchesAction:
      #   - String
      # GlobalFilters:
      #   PatchFilterGroup
      # Sources : PatchSource

  # CentosPatchBaseline:
  #   Type: "AWS::SSM::PatchBaseline"
  #   Properties:
  #     Name: cu-cit-cloud-team-patching-Centos
  #     # Options: WINDOWS, AMAZON_LINUX, AMAZON_LINUX_2, UBUNTU, REDHAT_ENTERPRISE_LINUX, SUSE, and CENTOS
  #     OperatingSystem: CENTOS
  #     Description: "Patch baseline for use with https://github.com/CU-CommunityApps/ct-patching-scanning"
  #     PatchGroups:
  #       - cu-cit-cloud-team-patching
  #     ApprovalRules:
  #       PatchRules:
  #         - PatchFilterGroup:
  #             # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
  #             # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
  #             PatchFilters:
  #               # - Key: PRODUCT
  #               #   Values:
  #               #     - "*"
  #               - Key: CLASSIFICATION
  #                 Values:
  #                   - Security
  #                   - Bugfix
  #                   - Recommended
  #                   - Enhancement
  #                   - Newpackage
  #           ApproveAfterDays: !Ref PatchApprovalDelayParam
  #           # ComplianceLevel: String
  #           EnableNonSecurity: true # this matches the AWS SSM default baseline for CentOS
  #     # ApprovedPatches:
  #     #   - String
  #     # ApprovedPatchesComplianceLevel: CRITICAL
  #     # ApprovedPatchesEnableNonSecurity: false
  #     # RejectedPatches:
  #     #   - String
  #     # RejectedPatchesAction:
  #     #   - String
  #     # GlobalFilters:
  #     #   PatchFilterGroup
  #     # Sources : PatchSource

  RHELPatchBaseline:
    Type: "AWS::SSM::PatchBaseline"
    Properties:
      Name: cu-cit-cloud-team-patching-RHEL
      # Options: WINDOWS, AMAZON_LINUX, AMAZON_LINUX_2, UBUNTU, REDHAT_ENTERPRISE_LINUX, SUSE, and CENTOS
      OperatingSystem: REDHAT_ENTERPRISE_LINUX
      Description: "Patch baseline for use with https://github.com/CU-CommunityApps/ct-patching-scanning"
      PatchGroups:
        - cu-cit-cloud-team-patching
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
              # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
              PatchFilters:
                # - Key: PRODUCT
                #   Values:
                #     - "*"
                - Key: CLASSIFICATION
                  Values:
                    - Security
            ApproveAfterDays: !Ref PatchApprovalDelayParam
            # ComplianceLevel: String
            # EnableNonSecurity: Boolean
          - PatchFilterGroup:
              # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
              # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
              PatchFilters:
                # - Key: PRODUCT
                #   Values:
                #     - "*"
                - Key: CLASSIFICATION
                  Values:
                    - Bugfix
            ApproveAfterDays: !Ref PatchApprovalDelayParam
            # ComplianceLevel: String
            # EnableNonSecurity: Boolean
      # ApprovedPatches:
      #   - String
      # ApprovedPatchesComplianceLevel: CRITICAL
      # ApprovedPatchesEnableNonSecurity: false
      # RejectedPatches:
      #   - String
      # RejectedPatchesAction:
      #   - String
      # GlobalFilters:
      #   PatchFilterGroup

  UbuntuPatchBaseline:
    Type: "AWS::SSM::PatchBaseline"
    Properties:
      Name: cu-cit-cloud-team-patching-Ubuntu
      # Options: WINDOWS, AMAZON_LINUX, AMAZON_LINUX_2, UBUNTU, REDHAT_ENTERPRISE_LINUX, SUSE, and CENTOS
      OperatingSystem: UBUNTU
      Description: "Patch baseline for use with https://github.com/CU-CommunityApps/ct-patching-scanning"
      PatchGroups:
        - cu-cit-cloud-team-patching
      ApprovalRules:
        PatchRules:
          - PatchFilterGroup:
              # See https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_PatchFilter.html
              # PRODUCT | CLASSIFICATION | MSRC_SEVERITY | PATCH_ID | SECTION | PRIORITY | SEVERITY
              PatchFilters:
                - Key: PRODUCT
                  Values:
                    - "*"
                - Key: PRIORITY
                  Values:
                    - Required
                    - Important
                    - Standard
                    - Optional
                    - Extra
                - Key: SECTION
                  Values:
                    - "*"
            ApproveAfterDays: !Ref PatchApprovalDelayParam
            # ComplianceLevel: String
            # EnableNonSecurity: Boolean
      # ApprovedPatches:
      #   - String
      # ApprovedPatchesComplianceLevel: CRITICAL
      # ApprovedPatchesEnableNonSecurity: false
      # RejectedPatches:
      #   - String
      # RejectedPatchesAction:
      #   - String
      # GlobalFilters:
      #   PatchFilterGroup
